package com.example.triage.model;

public enum ErrorClassification {
    SCHEMA_VALIDATION,
    DATA_QUALITY,
    MISSING_ASSET,
    AUTH,
    NETWORK_TIMEOUT,
    DEPENDENCY_FAILURE,
    INFRASTRUCTURE,
    CONFIGURATION,
    DUPLICATE_WORK_ITEM,
    UNSUPPORTED_PAYLOAD_TYPE,
    MALFORMED_XML,
    MANIFEST_MISMATCH,
    CHECKSUM_FAILURE,
    MEDIA_PROCESSING_FAILURE,
    TRANSFORMATION_FAILURE,
    DATABASE_WRITE_FAILURE,
    S3_OBJECT_MISSING,
    PERMISSION_POLICY_FAILURE,
    DOWNSTREAM_DELIVERY_REJECTION,
    UNKNOWN
}
